# Generated by Django 4.0.4 on 2022-06-01 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VicHubApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 17, 23, 51, 860145)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 6, 1, 17, 23, 51, 857154)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_promotion',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 17, 23, 51, 857153)),
        ),
    ]
