# Generated by Django 4.0.4 on 2022-06-01 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VicHubApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='belongsto',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 13, 22, 25, 905672)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 6, 1, 13, 22, 25, 905673)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_promotion',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 13, 22, 25, 905672)),
        ),
    ]
