# Generated by Django 4.0.4 on 2022-06-01 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VicHubApp', '0002_alter_grade_date_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 17, 24, 51, 883266)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 6, 1, 17, 24, 51, 880269)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_promotion',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 17, 24, 51, 880269)),
        ),
    ]
