# Generated by Django 4.0.4 on 2022-06-08 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VicHubApp', '0003_alter_grade_date_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='belongsto',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 18, 17, 46, 504536)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 6, 8, 18, 17, 46, 501551)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_promotion',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 18, 17, 46, 501551)),
        ),
    ]
