# Generated by Django 4.0.4 on 2022-05-29 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VicHubApp', '0005_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='belongsto',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 5, 29, 14, 47, 56, 82965)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_promotion',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 14, 47, 56, 82965)),
        ),
    ]
